{{- if .Values.webhooks.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "heist.webhooks.mutating" . }}
  labels:
    {{- include "heist.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.certmanager.enabled }}
    cert-manager.io/inject-ca-from: {{ printf "%s/%s" .Release.Namespace (include "heist.cert.name" .) }}
    {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      {{- if .Values.webhooks.caBundle }}
      caBundle: {{ .Values.webhooks.caBundle }}
      {{- end }}
      service:
        name: {{ include "heist.services.webhook" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-pod-agent-injector
    failurePolicy: Fail
    name: vpods.heist.youniqx.com
    namespaceSelector:
      matchLabels:
        heist.youniqx.com/inject-agent: "true"
        {{- if not .Values.scope.global }}
        heist.youniqx.com/operator: {{ .Release.Namespace }}
        {{- end }}
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
{{- end }}
