{{- if .Values.manager.enabled }}
{{- if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "heist.cert.name" . }}
  labels:
    {{- include "heist.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ printf "%s.%s.svc" (include "heist.services.webhook" .) .Release.Namespace }}
    - {{ printf "%s.%s.svc.cluster.local" (include "heist.services.webhook" .) .Release.Namespace }}
  issuerRef:
    kind: Issuer
    name: {{ include "heist.cert.issuer" . }}
  secretName: {{ include "heist.cert.secretName" . }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "heist.cert.issuer" . }}
  labels:
    {{- include "heist.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
{{- end }}
