{{/* vim: set filetype=helm: */}}
{{- if .Values.manager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heist.fullname" . }}
  labels:
  {{- include "heist.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "heist.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "heist.selectorLabels" . | nindent 8 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "heist.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: {{ include "heist.cert.secretName" . }}
        {{- if .Values.vault.ca.secret }}
        - name: vault-ca
          secret:
            defaultMode: 420
            secretName: {{ .Values.vault.ca.secret }}
        {{- end }}
        - name: cache
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.heist.securityContext | nindent 12 }}
          env:
            - name: VAULT_ADDRESS
              value: {{ .Values.vault.address | required "vault.address not set" | quote }}
            - name: VAULT_ROLE
              value: {{ .Values.vault.role | required "vault.role not set" | quote }}
            - name: OPERATOR_SYNC_SECRET_NAMESPACE_ALLOW_LIST
              value: {{ .Values.heist.config.syncSecretNamespaceAllowList | join "," | quote }}
            - name: WATCH_NAMESPACE
              value: {{ include "heist.watch.namespaces" . }}
          command: [ /bin/heist ]
          args:
            - operator
            - --health-probe-bind-address={{ printf ":%d" (.Values.heist.healthProbePort | int) }}
            - --metrics-bind-address={{ printf "127.0.0.1:%d" (.Values.heist.metricsPort | int) }}
            - --leader-elect
            {{- if .Values.vault.ca.secret }}
            - --vault-ca-cert=/etc/vault-ca/{{ .Values.vault.ca.key }}
            {{- end }}
          image: {{ .Values.heist.image.repository }}:{{ default (printf "v%s" .Chart.AppVersion) .Values.heist.image.tag }}
          imagePullPolicy: {{ .Values.heist.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.webhook.targetPort | int }}
              name: webhook-server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.heist.healthProbePort | int }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.heist.healthProbePort | int }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
          {{- toYaml .Values.heist.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            - mountPath: /home/nonroot/.cache
              name: cache
              readOnly: false
            - mountPath: /.cache
              name: cache
              readOnly: false
            {{- if .Values.vault.ca.secret }}
            - mountPath: /etc/vault-ca
              name: vault-ca
              readOnly: true
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
      {{- toYaml .Values.affinity | nindent 8 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - {{ include "heist.name" . }}
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - {{ .Release.Name }}
                topologyKey: kubernetes.io/hostname
              weight: 100
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
