{{- if .Values.manager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "heist.services.webhook" . }}
  labels:
    {{- include "heist.labels" . | nindent 4 }}
  annotations:
    {{- if not .Values.certmanager.enabled }}
    service.beta.openshift.io/serving-cert-secret-name: {{ include "heist.cert.secretName" . }}
    {{- end }}
spec:
  type: {{ .Values.services.webhook.type }}
  ports:
    - name: https
      port: {{ .Values.services.webhook.port }}
      targetPort: {{ .Values.services.webhook.targetPort }}
  selector:
    {{- include "heist.selectorLabels" . | nindent 4 }}
{{- end }}
