{{- if .Values.manager.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "heist.role.manager.leaderelection" . }}
  labels:
    {{- include "heist.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "heist.role.manager.leaderelection" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "heist.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
