{{- if .Values.managerRoles.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "heist.role.manager.kind.rolebinding" . }}
metadata:
  name: {{ include "heist.role.manager.operator" . }}
  labels:
    {{- include "heist.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ include "heist.role.manager.kind.role" . }}
  name: {{ include "heist.role.manager.operator" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "heist.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
