apiVersion: heist.youniqx.com/v1alpha1
kind: VaultCertificateAuthority
metadata:
  name: tls-root
spec:
  subject:
    common_name: tls-root
  settings:
    ttl: "20000h"
    key_bits: 4096
    key_type: rsa
---
apiVersion: heist.youniqx.com/v1alpha1
kind: VaultCertificateAuthority
metadata:
  name: tls-intermediate
spec:
  issuer: tls-root
  subject:
    common_name: tls-int
  settings:
    ttl: "10000h"
    key_bits: 4096
    key_type: rsa
---
apiVersion: heist.youniqx.com/v1alpha1
kind: VaultCertificate
metadata:
  name: tls-cert
spec:
  issuer: tls-intermediate
  settings:
    ttl: "120s"
    key_bits: 4096
    key_type: rsa
    allow_glob_domains: true
    allow_subdomains: true
    allow_bare_domains: true
    allowed_domains:
      - "example.com"
---
apiVersion: heist.youniqx.com/v1alpha1
kind: VaultSyncSecret
metadata:
  name: tls-secret-sync
secret:
  name: tls-secret
  type: kubernetes.io/tls
certificates:
  - name: tls-cert
    common_name: "*.example.com"
    alternative_names:
      - "example.com"
      - "*.example.com"
    fields:
      - field: private_key
        key: tls.key
      - field: certificate
        key: tls.crt
certificateAuthorities:
  - name: intermediate-ca
    fields:
      - field: full_cert_chain
        key: ca.crt
---
apiVersion: heist.youniqx.com/v1alpha1
kind: VaultCertificateAuthority
metadata:
  name: root-ca
spec:
  subject:
    common_name: some-root
  settings:
    key_bits: 2048
    key_type: rsa
---
apiVersion: heist.youniqx.com/v1alpha1
kind: VaultCertificateAuthority
metadata:
  name: intermediate-ca
spec:
  issuer: root-ca
  subject:
    common_name: some-intermediate
  settings:
    key_bits: 2048
    key_type: rsa
    exported: true
---
apiVersion: heist.youniqx.com/v1alpha1
kind: VaultSyncSecret
metadata:
  name: test-sync
secret:
  name: test-secret
certificateAuthorities:
  - name: intermediate-ca
    fields:
      - field: full_cert_chain
        key: ca.crt
---
apiVersion: heist.youniqx.com/v1alpha1
kind: VaultSyncSecret
metadata:
  name: other-namespace-sync
secret:
  name: synced-secret
  namespace: default
certificateAuthorities:
  - name: intermediate-ca
    fields:
      - field: full_cert_chain
        key: full_chain
  - name: intermediate-ca
    fields:
      - field: cert_chain
        key: chain
  - name: intermediate-ca
    fields:
      - field: certificate
        key: cert
  - name: intermediate-ca
    fields:
      - field: private_key
        key: key
---
apiVersion: heist.youniqx.com/v1alpha1
kind: VaultCertificate
metadata:
  name: some-cert
spec:
  issuer: intermediate-ca
  subject:
    organization:
      - youniqx Idenity AG
  settings:
    ttl: 60m
    key_bits: 2048
    key_type: rsa
    allow_bare_domains: true
    allowed_domains:
      - example.com
---
apiVersion: heist.youniqx.com/v1alpha1
kind: VaultCertificate
metadata:
  name: test-cert
spec:
  issuer: intermediate-ca
  subject:
    organization:
      - youniqx Idenity AG
  settings:
    ttl: 60m
    key_bits: 2048
    key_type: rsa
    allow_any_name: true
---
apiVersion: heist.youniqx.com/v1alpha1
kind: VaultKVSecretEngine
metadata:
  name: some-engine
spec:
  deleteProtection: false
  max_versions: 10
---
apiVersion: heist.youniqx.com/v1alpha1
kind: VaultSecret
metadata:
  name: some-secret
spec:
  engine: some-engine
  fields:
    some-field:
      autoGenerated: true
---
apiVersion: heist.youniqx.com/v1alpha1
kind: VaultBinding
metadata:
  name: some-binding
subjects:
  - name: some-sa
certificateAuthorities:
  - name: intermediate-ca
    fields:
      - field: certificate
        path: intermediate-cert
      - field: private_key
        path: intermediate-private-key
      - field: full_cert_chain
        path: /heist/secrets/some/path/chain
certificate:
  - name: some-cert
    common_name: example.com
    fields:
      - field: private_key
        path: privateKey
      - field: certificate
        path: publicKey
  - name: test-cert
    common_name: Document Signer
    fields:
      - field: private_key
        path: doc_sign.key
      - field: certificate
        path: doc_sign.crt
kv:
  - name: some-secret
    field: some-field
    path: some-value
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: some-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example
  name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
      annotations:
        youniqx.com/heist-agent-enabled: "true"
    spec:
      serviceAccountName: some-sa
      imagePullSecrets:
        - name: docker-secret
      securityContext:
        fsGroup: 2337
      containers:
        - image: ubuntu
          name: ubuntu
          securityContext:
            runAsUser: 1337
            runAsGroup: 2337
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          command:
            - sleep
          args:
            - "3600"
          resources: {}
